# Embedding

## Why Embedding?
As we know, machines can't handle text, it can only handle numbers. But how to convert a word to numbers?

The most naive approach would be to take a list of all the words in your text and attribute a number to all of them. It will work but you can imagine that some problems will appear:
* How do you handle unknown words? 
* If your text contains `doctor`, `nurse`, and `candy`. `doctor` and `nurse` have a strong similarity but `candy` doesn't. How can we make the machine understand that? With our naive technique, `doctor` could have the number `5` associated to it and nurse the number `98767`.

Of course, a lot of people already spent some time with those problems. the solution that came out of it is "Embedding". 

## What is embeddings?

An embedding is a **VECTOR** which represents a word or a document.

A vector will be attributed to each token. Each vector will contain multiple dimensions (usually tens or hundreds of dimensions).

```
[...] associate with each word in the vocabulary a distributed word feature vector [...] The feature vector represents different aspects of the word: each word is associated with a point in a vector space. The number of features [...] is much smaller than the size of the vocabulary.
```
- [A Neural Probabilistic Language Model](https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf), 2003.

Long story short, embeddings convert words into vectors in a way that allows the machine to understand the similarity betweens them.

Each embedding library has it's own way of classifying words, it will regroup words into big categories. Each word will get a score for each category.

To take a simple example the word `mother` could be classified like that:

|        | female | family | human | animal|
|--------|--------|---------|-------|-------|
| mother | 0.9    | 0.9.    | 0.7   | 0.1   |

**Explanations:** Mother has a strong similarity with female, family and human but it has a low similarity with animal.

**Disclaimer:** Those numbers and categories are totally arbitrary and are only here to show an example.

Here is another example with more complete datas:

![embedding](https://miro.medium.com/max/2598/1*sAJdxEsDjsPMioHyzlN3_A.png)

## Should I do it by hand?

You could, but if some people already did the job for you and spent a lot of time to optimize it, why not use it?

## What to use?

There are a lot of libraries out there for embeddings. Which one is the best? Once again, *it depends*. The results will change depending on the text you are using, the information you want to extract, the model you use,...

Choosing the "best" embedding model will be part of the hyper-optimization that you can do at the end of a project.

If you want understand embeddings more in depth, [follow this link](http://jalammar.github.io/illustrated-word2vec/)

Here are some of the best libraries of the moment:

* [Flair](https://github.com/flairNLP/flair) (University of Berlin)
* [fasttext](https://fasttext.cc/) (Facebook)
* [GloVe](https://github.com/stanfordnlp/GloVe) (Stanford)

And the oldest way doing it (but still good):
* [Word2Vec](https://www.tensorflow.org/tutorials/text/word2vec)

## Stack embeddings

The previous embeddings are good, but if you want something even better, you can "stack" these embeddings to create a bigger vector. It gives better results but will also require more computation power.

[Here is a super clear and understandable guide](https://github.com/flairNLP/flair/blob/master/resources/docs/TUTORIAL_3_WORD_EMBEDDING.md) to get it done. (by the Flair's team)

## Practice time!

Enough reading, let's practice a bit. Can you use SpaCy to embed this sentence?
Read the [spacy embedding documentation](https://spacy.io/usage/vectors-similarity)

In [5]:
sentence = "I love learning"

# Embed `sentence` with SpaCy



In [6]:
import spacy

nlp = spacy.load("en_core_web_sm")
tokens = nlp(sentence)

for token in tokens:
    print(token.text, token.has_vector, token.vector_norm, token.is_oov)

I True 8.277152 True
love True 7.836812 True
learning True 8.697989 True


In [7]:
for token in tokens:
    print(token.text, token.vector)

I [ 1.10176355e-01 -1.00206280e+00 -7.37348914e-01 -4.21369344e-01
  1.26815522e+00  1.01282895e-01  1.22158146e+00  9.41173211e-02
  6.11733913e-01  2.67086446e-01 -5.15017867e-01  9.33182955e-01
  1.34804058e+00  2.07552522e-01 -1.10650647e+00  2.18127221e-01
 -8.12490225e-01 -3.19170117e-01  6.82181120e-01 -6.72757030e-02
  6.34525537e-01 -1.26337200e-01 -2.08082974e-01 -1.03394032e+00
  2.46634698e+00  6.73271194e-02 -1.00889707e+00  2.34798193e-02
 -1.18598306e+00  6.71017766e-02 -6.87737346e-01 -2.94678241e-01
 -1.80477571e+00 -6.30941615e-02 -4.73648787e-01 -1.43817735e+00
 -9.56059933e-01  1.78785622e-01 -1.27222240e-01  8.63844812e-01
  1.01742697e+00  1.56876707e+00 -4.96611297e-01  4.25037891e-01
 -2.50088990e-01  1.40886888e-01 -7.53663301e-01 -5.81104994e-01
  9.16368961e-02 -9.78723586e-01  1.15381956e-01 -3.34213763e-01
  1.12113702e+00  2.86907703e-01  9.25659895e-01  3.18265676e+00
 -1.24204904e-03  2.87270963e-01  5.06109953e-01  3.47291678e-01
  6.93372667e-01 -6.360

What is the shape of each word's vector?

In [8]:
for token in tokens:
    print(token.vector.shape)

(96,)
(96,)
(96,)


Other code

In [12]:
# I tried this is not part of the material
from spacy.vectors import Vectors
import numpy as np
empty_vectors = Vectors(shape=(10000, 300))

data = np.zeros((3, 300), dtype='f')
keys = ["I", "love", "learning"]
vectors = Vectors(data=data, keys=keys)

In [13]:
vectors

What is the shape of each word's vector?

In [14]:
nlp(u'I').vector.shape

(96,)

## Try with Flair now

In [15]:
sentence = "I love learning"

In [2]:
from flair.embeddings import FlairEmbeddings
from flair.data import Sentence

# init embedding
flair_embedding_forward = FlairEmbeddings('news-forward')

# create a sentence
sentence = Sentence("I love learning")

# embed words in sentence
flair_embedding_forward.embed(sentence)

c:\Users\yurit\anaconda3\envs\myFlair\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[Sentence: "I love learning"]

In [3]:
# now check out the embedded tokens.
for token in sentence:
    print(token)
    print(token.embedding)
    print(token.embedding.shape)

Token[0]: "I"
tensor([ 0.0040,  0.0002,  0.0748,  ..., -0.0040,  0.0220,  0.0052],
       device='cuda:0')
torch.Size([2048])
Token[1]: "love"
tensor([-2.8628e-04, -8.3362e-05,  2.4467e-03,  ..., -3.9199e-03,
        -1.2964e-02,  4.7443e-03], device='cuda:0')
torch.Size([2048])
Token[2]: "learning"
tensor([-0.0001,  0.0002,  0.0244,  ..., -0.0041, -0.0057,  0.0073],
       device='cuda:0')
torch.Size([2048])


What is the shape of each word's vector?

In [5]:
# now check out the embedded tokens.
for token in sentence:
    print(token)
    print(token.embedding.shape)

torch.Size([2048])
torch.Size([2048])
torch.Size([2048])


Recommended Flair Usage

We recommend combining both forward and backward Flair embeddings. Depending on the task, we also recommend adding standard word embeddings into the mix. So, our recommended StackedEmbedding for most English tasks is:

In [6]:
from flair.embeddings import WordEmbeddings, FlairEmbeddings, StackedEmbeddings

# create a StackedEmbedding object that combines glove and forward/backward flair embeddings
stacked_embeddings = StackedEmbeddings([
                                        WordEmbeddings('glove'),
                                        FlairEmbeddings('news-forward'),
                                        FlairEmbeddings('news-backward'),
                                       ])

In [7]:
sentence = Sentence('I love learning')

# just embed a sentence using the StackedEmbedding as you would with any single embedding.
stacked_embeddings.embed(sentence)

# now check out the embedded tokens.
for token in sentence:
    print(token)
    print(token.embedding)

Token[0]: "I"
tensor([-0.0465,  0.6197,  0.5665,  ..., -0.0010, -0.0152, -0.0501],
       device='cuda:0')
Token[1]: "love"
tensor([ 0.2598,  0.5583,  0.5799,  ...,  0.0219, -0.0060, -0.0601],
       device='cuda:0')
Token[2]: "learning"
tensor([ 0.6481,  0.6988, -0.3995,  ...,  0.0016, -0.0222, -0.0022],
       device='cuda:0')


What is the shape of each word's vector?

In [8]:
# now check out the embedded tokens.
for token in sentence:
    print(token)
    print(token.embedding.shape)

Token[0]: "I"
torch.Size([4196])
Token[1]: "love"
torch.Size([4196])
Token[2]: "learning"
torch.Size([4196])


Do the same with Fasttext

In [ ]:
sentence = "I love learning"


# Embed `sentence` with Fasttext

What is the shape of each word's vector?

Do the same with GloVe

In [ ]:
sentence = "I love learning"


# Embed `sentence` with glove

What is the shape of each word's vector?

Your text is now embedded, your model will be able to understand it, yeah!


## Maths on text

Since the words are embedded into vectors we can now apply mathematical methods on them.

### Average vector

For example we could build the average vector for a text by using NumPy! This is a straightforward way to build one single representation for a text.

In [16]:
text = "I want to be a famous data scientist"

# Apply a spacy model on the text

# Get all word vectors into a list

# Compute and display the average vector of the text

In [17]:
import spacy

text = ("I want to be a famous data scientist")
# Apply a spacy model on the text
doc = nlp(text)

# Extract tokens for the given doc
print ([token.text for token in doc])

# Compute and display the average vector of the text
doc.vector   # Average vector of the text


['I', 'want', 'to', 'be', 'a', 'famous', 'data', 'scientist']


array([ 0.30562106, -0.46668267,  0.18118   ,  0.10908538,  0.41245294,
        0.03734358,  0.32639813, -0.13535896,  0.09729309, -0.05765083,
        0.2214193 , -0.04172044,  0.26377854,  0.49861214, -0.17263839,
       -0.15902124, -0.20183812,  0.03181725, -0.57855135,  0.04326862,
        0.907686  , -0.08480154,  0.12812576, -0.20969304,  0.4940275 ,
        0.03705223, -0.06355449,  0.14762354, -0.39961818, -0.27418312,
       -0.38811898,  0.05215233,  0.0750602 , -0.18713821, -0.53578055,
        0.22827083, -0.18803607, -0.19935909,  0.1113503 , -0.1084053 ,
        0.28453946,  0.1037382 , -0.48079926, -0.10080262,  0.16023256,
       -0.02597305,  0.41315472, -0.8075175 , -0.18440957,  0.03429174,
       -0.18987596, -0.2646015 , -0.08954486,  0.24843045,  0.00751189,
        0.34270817,  0.10769716,  0.07470732,  0.3089543 , -0.0607796 ,
       -0.09832704, -0.569713  , -0.2613706 ,  0.37682348, -0.17064035,
       -0.08847697,  0.00259911, -0.14756161, -0.42058748, -0.42

In [40]:
import spacy 

text = "I want to be a famous data scientist"

# Apply a spacy model on the text
nlp = spacy.load("en_core_web_sm")  # or "en_core_web_lg"

# Get all word vectors into a list  
doc = nlp(text)

# Compute and display the average vector of the text
doc.vector

array([ 0.30562106, -0.46668267,  0.18118   ,  0.10908538,  0.41245294,
        0.03734358,  0.32639813, -0.13535896,  0.09729309, -0.05765083,
        0.2214193 , -0.04172044,  0.26377854,  0.49861214, -0.17263839,
       -0.15902124, -0.20183812,  0.03181725, -0.57855135,  0.04326862,
        0.907686  , -0.08480154,  0.12812576, -0.20969304,  0.4940275 ,
        0.03705223, -0.06355449,  0.14762354, -0.39961818, -0.27418312,
       -0.38811898,  0.05215233,  0.0750602 , -0.18713821, -0.53578055,
        0.22827083, -0.18803607, -0.19935909,  0.1113503 , -0.1084053 ,
        0.28453946,  0.1037382 , -0.48079926, -0.10080262,  0.16023256,
       -0.02597305,  0.41315472, -0.8075175 , -0.18440957,  0.03429174,
       -0.18987596, -0.2646015 , -0.08954486,  0.24843045,  0.00751189,
        0.34270817,  0.10769716,  0.07470732,  0.3089543 , -0.0607796 ,
       -0.09832704, -0.569713  , -0.2613706 ,  0.37682348, -0.17064035,
       -0.08847697,  0.00259911, -0.14756161, -0.42058748, -0.42

### Word similarity

We can also compute the similarity between two words by using distance measures (e.g. [cosine distance](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cosine.html), [euclidean distance](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.euclidean.html)...). These measures will calculate the distance between word embeddings in the vector space.

#### Let's practice!

In [38]:
# Import the required libraries
nlp = spacy.load("en_core_web_sm")
from scipy.spatial import distance

word1 = "computer"
word2 = "keyboard"

# Get the vector for both words through your favorite model
w1 = nlp(word1).vector
w2 = nlp(word2).vector

# Compute the cosine and the euclidean distance between both words
distance.cosine(w1, w2)

# Try with other pairs of words for comparing the results

0.4019054174423218

In [39]:
distance.euclidean(w1, w2)

6.418715000152588

In [20]:
# I think is better use Similarity
# Import the required libraries
import spacy
nlp_lg = spacy.load("en_core_web_lg")

word1 = "computer"
word2 = "keyboard"

# Get the vector for both words through your favorite model
word1_vector = nlp_lg(word1)
word2_vector = nlp_lg(word2)

# Compute the cosine and the euclidean distance between both words
word1_vector.similarity(word2_vector)

# Try with other pairs of words for comparing the results



0.5425749392020239

In [31]:
word1 = "brave"
word2 = "courageous"

word1_vector = nlp_lg(word1)
word2_vector = nlp_lg(word2)

word1_vector.similarity(word2_vector)

0.8416876491960881

## More resources
* [Why do we use word embeddings in NLP?](https://towardsdatascience.com/why-do-we-use-embeddings-in-nlp-2f20e1b632d2)
* [More details on what word embeddings are exactly?](https://www.analyticsvidhya.com/blog/2017/06/word-embeddings-count-word2veec/)