## Exercise 4
Let's dive into the serious business now!

### Description
[Kaggle](http://www.kagle.com/) is a great platform to learn machine learning. They offer free datasets and organize competitions around them. You can even be paid if you win one of them!

Now that you know how to build a classifier, try with [the titanic dataset!](https://www.kaggle.com/c/titanic).

### Steps
1. Download the dataset.
2. Import it in a jupyter notebook.
3. Analyse the data.
4. Divide the dataset. (train data and test data)
5. Build a classifier using the algorithm of you choice and fit it with your train data.
6. Evaluate the model with your test data.
7. When you're satisfied with the result, fit your model with the complete dataset.
8. Predict the Kaggle's test set and [submit your prediciton](https://www.kaggle.com/c/titanic/overview).
9. Which score did you get?

**DISCLAIMER:** If you look at Kaggle's leaderboard, you will see a lot of people have a score of 100%. They just found the name of people that survived online. Great lesson here, when you are learning something, never compare yourself to others. All that matters is what you've learned.

In [1]:
import seaborn as sns
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
import warnings

In [2]:
np.random.seed(18)
warnings.filterwarnings('ignore')
sns.set()

In [12]:
df= pd.read_csv('./titanic/train.csv')
df_train = df
df= pd.read_csv('./titanic/test.csv')
df_test = df

In [13]:
df_train.shape

(891, 12)

In [14]:
df_test.shape

(418, 11)

In [6]:
df_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [16]:
df_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [8]:
df_train.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [9]:
col_names = ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked']
for col in col_names:
    print(df[col].value_counts())   

0    549
1    342
Name: Survived, dtype: int64
3    491
1    216
2    184
Name: Pclass, dtype: int64
male      577
female    314
Name: Sex, dtype: int64
0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: SibSp, dtype: int64
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: Parch, dtype: int64
347082      7
CA. 2343    7
1601        7
3101295     6
CA 2144     6
           ..
9234        1
19988       1
2693        1
PC 17612    1
370376      1
Name: Ticket, Length: 681, dtype: int64
B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: Cabin, Length: 147, dtype: int64
S    644
C    168
Q     77
Name: Embarked, dtype: int64


In [11]:
for col in df_train.columns:     
        if len(df_train[col].unique()) <100:
                print ("##############", df_train[col].name, "##############")   #\n
                print (df_train[col].unique(), "\n")

############## Survived ##############
[0 1] 

############## Pclass ##############
[3 1 2] 

############## Sex ##############
['male' 'female'] 

############## Age ##############
[22.   38.   26.   35.     nan 54.    2.   27.   14.    4.   58.   20.
 39.   55.   31.   34.   15.   28.    8.   19.   40.   66.   42.   21.
 18.    3.    7.   49.   29.   65.   28.5   5.   11.   45.   17.   32.
 16.   25.    0.83 30.   33.   23.   24.   46.   59.   71.   37.   47.
 14.5  70.5  32.5  12.    9.   36.5  51.   55.5  40.5  44.    1.   61.
 56.   50.   36.   45.5  20.5  62.   41.   52.   63.   23.5   0.92 43.
 60.   10.   64.   13.   48.    0.75 53.   57.   80.   70.   24.5   6.
  0.67 30.5   0.42 34.5  74.  ] 

############## SibSp ##############
[1 0 3 4 2 5 8] 

############## Parch ##############
[0 1 2 5 3 4 6] 

############## Embarked ##############
['S' 'C' 'Q' nan] 



Resources:  
  
[Basic Feature Engineering Titanic Data](https://triangleinequality.wordpress.com/2013/09/08/basic-feature-engineering-with-the-titanic-data/)

[Titanic (top 8%)](https://www.kaggle.com/code/akhileshthite/titanic-solution-top-8/notebook)