# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
import numpy
print(numpy.__version__)

1.21.5


#### 3. Create a null vector of size 10 (★☆☆)

In [27]:
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [10]:
print(zeros.size)

10


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [26]:
#x=np.zeros(10)
#x[4]=1
#x

y = numpy.eye( 10 ) [ 5 - 1 ]  # numpy.eye returns the identity matrix
y


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
z = np.arange(10, 50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [21]:
np.random.seed(0)
x1 = np.random.randint(8, size=(3,3))  
x1


array([[4, 7, 5],
       [0, 3, 3],
       [3, 7, 1]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [36]:
w = np.array([1,2,0,0,4,0])
np.nonzero(w)

#w[np.nonzero(w)]
#np.transpose(np.nonzero(w))

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [39]:
np.random.random((3,3,3))

array([[[0.61306346, 0.90234858, 0.09928035],
        [0.96980907, 0.65314004, 0.17090959],
        [0.35815217, 0.75068614, 0.60783067]],

       [[0.32504723, 0.03842543, 0.63427406],
        [0.95894927, 0.65279032, 0.63505887],
        [0.99529957, 0.58185033, 0.41436859]],

       [[0.4746975 , 0.6235101 , 0.33800761],
        [0.67475232, 0.31720174, 0.77834548],
        [0.94957105, 0.66252687, 0.01357164]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [42]:
b = np.random.random((10,10))
for func in (b.min, b.max):
    print(func.__name__, "=", func())


min = 0.004048106368426341
max = 0.9850322788832359


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [46]:
c = np.random.random(30)
print(c)
print("mean =", c.mean())

[0.91672702 0.11381664 0.63112554 0.132815   0.37424458 0.32440486
 0.68011554 0.79553475 0.50393361 0.29624239 0.88596227 0.35187056
 0.73839034 0.55536126 0.20151771 0.5485191  0.51964283 0.34878266
 0.02461996 0.1488293  0.13185204 0.70791746 0.70907211 0.61174841
 0.67190702 0.44751587 0.69607717 0.37832614 0.10003205 0.96025678]
mean = 0.4835720328801528


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [53]:
w = np.ones((5,5))
print("Original array:")
print(w)
print("1 on the border and 0 inside in the array")
w[1:-1,1:-1] = 0
print(w)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Note_yuri: # https://numpy.org/doc/stable/reference/generated/numpy.pad.html

In [54]:
w = np.pad(w, pad_width=1, mode= 'constant', constant_values=0) 
print(w)    

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [60]:
# np.nan Handling missing values
# The nan stands for “not a number“
# NaNs can be used as a poor-man’s mask (if you don’t care what the original value was)
print(0 * np.nan)     # convert nan value to zero  = nan
print(np.nan == np.nan)  # False. all our elements have been converted to float data types/A floating point representation of Not a Number.
print(np.inf > np.nan) # False. # infinity but it cannot be compared to a thing " nothing " with respect to a number! # False: exception due to logical error
print(np.inf != np.nan) 

print(np.nan - np.nan)  # nan # NaNs can be used as a poor-man’s mask (if you don’t care what the original value was)
print(np.nan in set([np.nan])) # True. np.nan is just a name for float('nan'),
print(0.3 == 3 * 0.1)  #False because some floating-point numbers cannot be represented exactly.
#The reason is that only numbers that are powers of 2 can be represented precisely with a simple binary representation.
#The individual digits of a binary number are different powers of 2 and any number is thus a sum of different powers of 2.

nan
False
False
True
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [57]:
w = np.diag(1+np.arange(4), k = -1)
print(w)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
note_yuri: [::2] 2 is the step

In [76]:
checkerboard = np.zeros ((8,8), dtype=int)   # 2  dimensions
checkerboard[1::2, ::2]= 1     #  x[start:stop:step]  #ROW
checkerboard[::2, 1::2] = 1    # column
print (checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
note_yuri: the array contains 336 elements

In [75]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [77]:
# The tile() function is used to construct an array 
# by repeating A the number of times given by reps.
array= np.array([[0,1], [1,0]])    
b = np.tile(array,(4,4))      
b

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

Note_yuri: There are different methods to normalize.

In [83]:
from sklearn.preprocessing import normalize
a = np.random.random((5,5))

amax, amin = a.max(), a.min()
a= (a-amin)/(amax-amin)
print(a)

# different
a = normalize(a, axis=0, norm='max')
print(a)


[[0.59306896 0.3456252  0.65978061 0.6548885  0.83081753]
 [0.39574313 0.0164873  1.         0.44286542 0.95119503]
 [0.67537996 0.25443685 0.56324797 0.97123542 0.09532984]
 [0.26018224 0.06269221 0.77219725 0.         0.12000984]
 [0.24813511 0.88208122 0.16379096 0.4274293  0.3151061 ]]
[[0.87812639 0.39182922 0.65978061 0.67428399 0.87344603]
 [0.58595628 0.01869136 1.         0.45598153 1.        ]
 [1.         0.28845059 0.56324797 1.         0.10022113]
 [0.38523832 0.07107306 0.77219725 0.         0.12616744]
 [0.36740076 1.         0.16379096 0.44008825 0.33127392]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [111]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['alpha'])
type(color)

3


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [112]:
A = np.dot(np.ones((5,3)), np.ones((3,2)))
print (A)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [122]:
array = np.arange(15)
print(array)
array[(array>=3) & (array<=8)]*= (-1)
print(array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [141]:
print(sum(range(5),-1))    #  9    = 0+1+2+3+4
from numpy import *
print(sum(range(5),-1))    #  10

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [160]:
Z = np.arange(8)
print(Z)        # [0 1 2]
print("Z**Z ", Z**Z)        # = [0^0, 1^1, 2^2] = [1, 1, 4]
print("2 << Z >> 2 ", 2 << Z >> 2) # [0,1,2]
print("Z <- Z ", Z <- Z)  # 1 < -1 = FALSE
print("Z >- Z", Z >- Z)  # 0 > -0 = False, 1>-1 = True, 2>-2 = False, ....
print("1j * Z ", 1j * Z)  # [0.+0.j 0.+1.j 0.+2.j]
print("Z/1/1 ", Z/1/1)   # [0. 1. 2.] 
#print(Z<Z>Z)  # ValueError. The truth value of an array with more than one element is ambiguous. 

[0 1 2 3 4 5 6 7]
Z**Z  [     1      1      4     27    256   3125  46656 823543]
2 << Z >> 2  [ 0  1  2  4  8 16 32 64]
Z <- Z  [False False False False False False False False]
Z >- Z [False  True  True  True  True  True  True  True]
1j * Z  [0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j]
Z/1/1  [0. 1. 2. 3. 4. 5. 6. 7.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

note_yuri: https://stackoverflow.com/questions/45205289/why-converting-np-nan-to-int-results-in-huge-number

In [137]:
#print(np.array(0) / np.array(0))    # dtype=object #invalid value encountered in true_divide
#print(np.array(0) // np.array(0))    # RuntimeWarning: divide by zero encountered in floor_divide
print(np.array([np.nan]).astype(int).astype(float))  #array([-2.14748365e+09])  = -2147483650 = -2**31


# the way to convert all the nan values to 0 instead to a biger number (as the previous example)
a = np.array(['1','2','3','nan','nan'])
a[a=='nan'] = 0 # this will convert all the nan values to 0, or choose another number
a = a.astype('int')



[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

In [142]:
array = np.random.random((5,5))
print(array)
array = np.round(array,1)
print(array) 

#x = np.random.uniform(-10, +10, 10)
#np.copysign(np.ceil(np.abs(x)), x)

array([ 4.,  2.,  6.,  9., -2.,  8., -9.,  4., -6.,  1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [138]:
array1 = np.array([0, 1, 2, 3, 4])
array2 = [1, 3, 4]
  
# Common values between two arrays
print(np.intersect1d(array1, array2))


[1 3 4]
